<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.linked-planet.client</groupId>
        <artifactId>kotlin-atlassian-client</artifactId>
        <version>0.15.6</version>
    </parent>

    <artifactId>kotlin-http-client</artifactId>
    <name>kotlin-http-client</name>
    <packaging>pom</packaging>
    <description>Provides a client for jira rest api calls and object mapping.</description>
    <modules>
        <module>kotlin-http-client-api</module>
        <module>kotlin-http-client-atlas</module>
        <module>kotlin-http-client-ktor</module>
    </modules>

    <build>
        <plugins>
            <!-- flatten to produce explicit version numbers that are expected by central for publishing -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${maven.flatten.version}</version>
                <configuration>
                    <pomElements>
                        <scm/>
                        <url/>
                        <organization/>
                        <name/>
                        <description/>
                        <developers/>
                    </pomElements>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                        <phase>validate</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
